# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'analoggaugewidget_demo.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 712)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = AnalogGaugeWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(100, 100))
        self.widget.setMaximumSize(QtCore.QSize(600, 600))
        self.widget.setBaseSize(QtCore.QSize(300, 300))
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.gridLayout_4.addLayout(self.verticalLayout, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem1, 0, 3, 1, 1)
        self.Parameter = QtWidgets.QTabWidget(self.centralwidget)
        self.Parameter.setObjectName("Parameter")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_9.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_9.setLineWidth(0)
        self.lcdNumber_9.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.gridLayout.addWidget(self.lcdNumber_9, 6, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lcdNumber_4 = QtWidgets.QLCDNumber(self.tab_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_4.setFont(font)
        self.lcdNumber_4.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_4.setLineWidth(0)
        self.lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.gridLayout.addWidget(self.lcdNumber_4, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.horizontalSlider_5 = QtWidgets.QSlider(self.tab_3)
        self.horizontalSlider_5.setMaximum(200)
        self.horizontalSlider_5.setProperty("value", 0)
        self.horizontalSlider_5.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_5.setObjectName("horizontalSlider_5")
        self.gridLayout.addWidget(self.horizontalSlider_5, 1, 1, 1, 1)
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_3.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_3.setLineWidth(0)
        self.lcdNumber_3.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.gridLayout.addWidget(self.lcdNumber_3, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.GaugeStartSlider = QtWidgets.QSlider(self.tab_3)
        self.GaugeStartSlider.setMaximum(360)
        self.GaugeStartSlider.setProperty("value", 0)
        self.GaugeStartSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GaugeStartSlider.setObjectName("GaugeStartSlider")
        self.gridLayout.addWidget(self.GaugeStartSlider, 4, 1, 1, 1)
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_2.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_2.setLineWidth(0)
        self.lcdNumber_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.gridLayout.addWidget(self.lcdNumber_2, 2, 2, 1, 1)
        self.AussenRadiusSlider = QtWidgets.QSlider(self.tab_3)
        self.AussenRadiusSlider.setMaximum(1000)
        self.AussenRadiusSlider.setProperty("value", 0)
        self.AussenRadiusSlider.setOrientation(QtCore.Qt.Horizontal)
        self.AussenRadiusSlider.setObjectName("AussenRadiusSlider")
        self.gridLayout.addWidget(self.AussenRadiusSlider, 2, 1, 1, 1)
        self.InnenRadiusSlider = QtWidgets.QSlider(self.tab_3)
        self.InnenRadiusSlider.setMaximum(1000)
        self.InnenRadiusSlider.setProperty("value", 0)
        self.InnenRadiusSlider.setOrientation(QtCore.Qt.Horizontal)
        self.InnenRadiusSlider.setObjectName("InnenRadiusSlider")
        self.gridLayout.addWidget(self.InnenRadiusSlider, 3, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout.addWidget(self.lcdNumber, 3, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.ActualSlider = QtWidgets.QSlider(self.tab_3)
        self.ActualSlider.setMaximum(200)
        self.ActualSlider.setProperty("value", 0)
        self.ActualSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ActualSlider.setObjectName("ActualSlider")
        self.gridLayout.addWidget(self.ActualSlider, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
        self.lcdNumber_8 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_8.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_8.setLineWidth(0)
        self.lcdNumber_8.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.gridLayout.addWidget(self.lcdNumber_8, 5, 2, 1, 1)
        self.GaugeSizeSlider = QtWidgets.QSlider(self.tab_3)
        self.GaugeSizeSlider.setMaximum(360)
        self.GaugeSizeSlider.setProperty("value", 0)
        self.GaugeSizeSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GaugeSizeSlider.setObjectName("GaugeSizeSlider")
        self.gridLayout.addWidget(self.GaugeSizeSlider, 5, 1, 1, 1)
        self.offsetSlider = QtWidgets.QSlider(self.tab_3)
        self.offsetSlider.setMinimum(-360)
        self.offsetSlider.setMaximum(360)
        self.offsetSlider.setOrientation(QtCore.Qt.Horizontal)
        self.offsetSlider.setObjectName("offsetSlider")
        self.gridLayout.addWidget(self.offsetSlider, 6, 1, 1, 1)
        self.lcdNumber_7 = QtWidgets.QLCDNumber(self.tab_3)
        self.lcdNumber_7.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_7.setLineWidth(0)
        self.lcdNumber_7.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.gridLayout.addWidget(self.lcdNumber_7, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.CB_ScaleText = QtWidgets.QCheckBox(self.tab_3)
        self.CB_ScaleText.setChecked(True)
        self.CB_ScaleText.setObjectName("CB_ScaleText")
        self.gridLayout_6.addWidget(self.CB_ScaleText, 5, 0, 1, 1)
        self.CB_Needle = QtWidgets.QCheckBox(self.tab_3)
        self.CB_Needle.setChecked(True)
        self.CB_Needle.setObjectName("CB_Needle")
        self.gridLayout_6.addWidget(self.CB_Needle, 0, 2, 1, 1)
        self.CB_ShowBarGraph = QtWidgets.QCheckBox(self.tab_3)
        self.CB_ShowBarGraph.setChecked(True)
        self.CB_ShowBarGraph.setObjectName("CB_ShowBarGraph")
        self.gridLayout_6.addWidget(self.CB_ShowBarGraph, 0, 1, 1, 1)
        self.CB_barGraph = QtWidgets.QCheckBox(self.tab_3)
        self.CB_barGraph.setChecked(True)
        self.CB_barGraph.setObjectName("CB_barGraph")
        self.gridLayout_6.addWidget(self.CB_barGraph, 0, 0, 1, 1)
        self.CB_ValueText = QtWidgets.QCheckBox(self.tab_3)
        self.CB_ValueText.setChecked(True)
        self.CB_ValueText.setObjectName("CB_ValueText")
        self.gridLayout_6.addWidget(self.CB_ValueText, 2, 0, 1, 1)
        self.CB_CenterPoint = QtWidgets.QCheckBox(self.tab_3)
        self.CB_CenterPoint.setChecked(True)
        self.CB_CenterPoint.setObjectName("CB_CenterPoint")
        self.gridLayout_6.addWidget(self.CB_CenterPoint, 4, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem2, 3, 3, 1, 1)
        self.CB_Grid = QtWidgets.QCheckBox(self.tab_3)
        self.CB_Grid.setChecked(True)
        self.CB_Grid.setObjectName("CB_Grid")
        self.gridLayout_6.addWidget(self.CB_Grid, 6, 0, 1, 1)
        self.CB_fineGrid = QtWidgets.QCheckBox(self.tab_3)
        self.CB_fineGrid.setChecked(True)
        self.CB_fineGrid.setObjectName("CB_fineGrid")
        self.gridLayout_6.addWidget(self.CB_fineGrid, 7, 0, 1, 1)
        self.gridLayout_16.addLayout(self.gridLayout_6, 1, 0, 1, 1)
        self.ActualValue = QtWidgets.QLCDNumber(self.tab_3)
        self.ActualValue.setStyleSheet("QLCDNumber {\n"
"    border: 2px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.ActualValue.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ActualValue.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.ActualValue.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.ActualValue.setObjectName("ActualValue")
        self.gridLayout_16.addWidget(self.ActualValue, 2, 0, 1, 1)
        self.Parameter.addTab(self.tab_3, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.lcdNumber_Red_Needle = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Red_Needle.setFont(font)
        self.lcdNumber_Red_Needle.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Red_Needle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Red_Needle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Red_Needle.setLineWidth(0)
        self.lcdNumber_Red_Needle.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Red_Needle.setObjectName("lcdNumber_Red_Needle")
        self.gridLayout_2.addWidget(self.lcdNumber_Red_Needle, 0, 2, 1, 1)
        self.GreenSlider_Needle = QtWidgets.QSlider(self.groupBox)
        self.GreenSlider_Needle.setMaximum(255)
        self.GreenSlider_Needle.setProperty("value", 50)
        self.GreenSlider_Needle.setOrientation(QtCore.Qt.Horizontal)
        self.GreenSlider_Needle.setObjectName("GreenSlider_Needle")
        self.gridLayout_2.addWidget(self.GreenSlider_Needle, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.lcdNumber_Green_Needle = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Green_Needle.setFont(font)
        self.lcdNumber_Green_Needle.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Green_Needle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Green_Needle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Green_Needle.setLineWidth(0)
        self.lcdNumber_Green_Needle.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Green_Needle.setObjectName("lcdNumber_Green_Needle")
        self.gridLayout_2.addWidget(self.lcdNumber_Green_Needle, 1, 2, 1, 1)
        self.lcdNumber_Blue_Needle = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Blue_Needle.setFont(font)
        self.lcdNumber_Blue_Needle.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Blue_Needle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Blue_Needle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Blue_Needle.setLineWidth(0)
        self.lcdNumber_Blue_Needle.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Blue_Needle.setObjectName("lcdNumber_Blue_Needle")
        self.gridLayout_2.addWidget(self.lcdNumber_Blue_Needle, 2, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.BlueSlider_Needle = QtWidgets.QSlider(self.groupBox)
        self.BlueSlider_Needle.setMaximum(255)
        self.BlueSlider_Needle.setProperty("value", 50)
        self.BlueSlider_Needle.setOrientation(QtCore.Qt.Horizontal)
        self.BlueSlider_Needle.setObjectName("BlueSlider_Needle")
        self.gridLayout_2.addWidget(self.BlueSlider_Needle, 2, 1, 1, 1)
        self.TrancSlider_Needle = QtWidgets.QSlider(self.groupBox)
        self.TrancSlider_Needle.setMaximum(255)
        self.TrancSlider_Needle.setProperty("value", 255)
        self.TrancSlider_Needle.setOrientation(QtCore.Qt.Horizontal)
        self.TrancSlider_Needle.setObjectName("TrancSlider_Needle")
        self.gridLayout_2.addWidget(self.TrancSlider_Needle, 3, 1, 1, 1)
        self.lcdNumber_Trancparency_Needle = QtWidgets.QLCDNumber(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Trancparency_Needle.setFont(font)
        self.lcdNumber_Trancparency_Needle.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Trancparency_Needle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Trancparency_Needle.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Trancparency_Needle.setLineWidth(0)
        self.lcdNumber_Trancparency_Needle.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Trancparency_Needle.setObjectName("lcdNumber_Trancparency_Needle")
        self.gridLayout_2.addWidget(self.lcdNumber_Trancparency_Needle, 3, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.RedSlider_Needle = QtWidgets.QSlider(self.groupBox)
        self.RedSlider_Needle.setMaximum(255)
        self.RedSlider_Needle.setProperty("value", 50)
        self.RedSlider_Needle.setOrientation(QtCore.Qt.Horizontal)
        self.RedSlider_Needle.setObjectName("RedSlider_Needle")
        self.gridLayout_2.addWidget(self.RedSlider_Needle, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_16 = QtWidgets.QLabel(self.groupBox_2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_10.addWidget(self.label_16, 1, 0, 1, 1)
        self.lcdNumber_Red_NeedleDrag = QtWidgets.QLCDNumber(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Red_NeedleDrag.setFont(font)
        self.lcdNumber_Red_NeedleDrag.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Red_NeedleDrag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Red_NeedleDrag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Red_NeedleDrag.setLineWidth(0)
        self.lcdNumber_Red_NeedleDrag.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Red_NeedleDrag.setObjectName("lcdNumber_Red_NeedleDrag")
        self.gridLayout_10.addWidget(self.lcdNumber_Red_NeedleDrag, 0, 2, 1, 1)
        self.GreenSlider_NeedleDrag = QtWidgets.QSlider(self.groupBox_2)
        self.GreenSlider_NeedleDrag.setMaximum(255)
        self.GreenSlider_NeedleDrag.setProperty("value", 50)
        self.GreenSlider_NeedleDrag.setOrientation(QtCore.Qt.Horizontal)
        self.GreenSlider_NeedleDrag.setObjectName("GreenSlider_NeedleDrag")
        self.gridLayout_10.addWidget(self.GreenSlider_NeedleDrag, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_10.addWidget(self.label_17, 3, 0, 1, 1)
        self.lcdNumber_Green_NeedleDrag = QtWidgets.QLCDNumber(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Green_NeedleDrag.setFont(font)
        self.lcdNumber_Green_NeedleDrag.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Green_NeedleDrag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Green_NeedleDrag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Green_NeedleDrag.setLineWidth(0)
        self.lcdNumber_Green_NeedleDrag.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Green_NeedleDrag.setObjectName("lcdNumber_Green_NeedleDrag")
        self.gridLayout_10.addWidget(self.lcdNumber_Green_NeedleDrag, 1, 2, 1, 1)
        self.lcdNumber_Blue_NeedleDrag = QtWidgets.QLCDNumber(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Blue_NeedleDrag.setFont(font)
        self.lcdNumber_Blue_NeedleDrag.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Blue_NeedleDrag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Blue_NeedleDrag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Blue_NeedleDrag.setLineWidth(0)
        self.lcdNumber_Blue_NeedleDrag.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Blue_NeedleDrag.setObjectName("lcdNumber_Blue_NeedleDrag")
        self.gridLayout_10.addWidget(self.lcdNumber_Blue_NeedleDrag, 2, 2, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_10.addWidget(self.label_18, 2, 0, 1, 1)
        self.BlueSlider_NeedleDrag = QtWidgets.QSlider(self.groupBox_2)
        self.BlueSlider_NeedleDrag.setMaximum(255)
        self.BlueSlider_NeedleDrag.setProperty("value", 50)
        self.BlueSlider_NeedleDrag.setOrientation(QtCore.Qt.Horizontal)
        self.BlueSlider_NeedleDrag.setObjectName("BlueSlider_NeedleDrag")
        self.gridLayout_10.addWidget(self.BlueSlider_NeedleDrag, 2, 1, 1, 1)
        self.TrancSlider_NeedleDrag = QtWidgets.QSlider(self.groupBox_2)
        self.TrancSlider_NeedleDrag.setMaximum(255)
        self.TrancSlider_NeedleDrag.setProperty("value", 255)
        self.TrancSlider_NeedleDrag.setOrientation(QtCore.Qt.Horizontal)
        self.TrancSlider_NeedleDrag.setObjectName("TrancSlider_NeedleDrag")
        self.gridLayout_10.addWidget(self.TrancSlider_NeedleDrag, 3, 1, 1, 1)
        self.lcdNumber_Trancparency_NeedleDrag = QtWidgets.QLCDNumber(self.groupBox_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Trancparency_NeedleDrag.setFont(font)
        self.lcdNumber_Trancparency_NeedleDrag.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Trancparency_NeedleDrag.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Trancparency_NeedleDrag.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Trancparency_NeedleDrag.setLineWidth(0)
        self.lcdNumber_Trancparency_NeedleDrag.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Trancparency_NeedleDrag.setObjectName("lcdNumber_Trancparency_NeedleDrag")
        self.gridLayout_10.addWidget(self.lcdNumber_Trancparency_NeedleDrag, 3, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_10.addWidget(self.label_19, 0, 0, 1, 1)
        self.RedSlider_NeedleDrag = QtWidgets.QSlider(self.groupBox_2)
        self.RedSlider_NeedleDrag.setMaximum(255)
        self.RedSlider_NeedleDrag.setProperty("value", 50)
        self.RedSlider_NeedleDrag.setOrientation(QtCore.Qt.Horizontal)
        self.RedSlider_NeedleDrag.setObjectName("RedSlider_NeedleDrag")
        self.gridLayout_10.addWidget(self.RedSlider_NeedleDrag, 0, 1, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_10, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_20 = QtWidgets.QLabel(self.groupBox_3)
        self.label_20.setObjectName("label_20")
        self.gridLayout_12.addWidget(self.label_20, 1, 0, 1, 1)
        self.lcdNumber_Red_Scale = QtWidgets.QLCDNumber(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Red_Scale.setFont(font)
        self.lcdNumber_Red_Scale.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Red_Scale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Red_Scale.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Red_Scale.setLineWidth(0)
        self.lcdNumber_Red_Scale.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Red_Scale.setObjectName("lcdNumber_Red_Scale")
        self.gridLayout_12.addWidget(self.lcdNumber_Red_Scale, 0, 2, 1, 1)
        self.GreenSlider_Scale = QtWidgets.QSlider(self.groupBox_3)
        self.GreenSlider_Scale.setMaximum(255)
        self.GreenSlider_Scale.setProperty("value", 50)
        self.GreenSlider_Scale.setOrientation(QtCore.Qt.Horizontal)
        self.GreenSlider_Scale.setObjectName("GreenSlider_Scale")
        self.gridLayout_12.addWidget(self.GreenSlider_Scale, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox_3)
        self.label_21.setObjectName("label_21")
        self.gridLayout_12.addWidget(self.label_21, 3, 0, 1, 1)
        self.lcdNumber_Green_Scale = QtWidgets.QLCDNumber(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Green_Scale.setFont(font)
        self.lcdNumber_Green_Scale.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Green_Scale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Green_Scale.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Green_Scale.setLineWidth(0)
        self.lcdNumber_Green_Scale.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Green_Scale.setObjectName("lcdNumber_Green_Scale")
        self.gridLayout_12.addWidget(self.lcdNumber_Green_Scale, 1, 2, 1, 1)
        self.lcdNumber_Blue_Scale = QtWidgets.QLCDNumber(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Blue_Scale.setFont(font)
        self.lcdNumber_Blue_Scale.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Blue_Scale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Blue_Scale.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Blue_Scale.setLineWidth(0)
        self.lcdNumber_Blue_Scale.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Blue_Scale.setObjectName("lcdNumber_Blue_Scale")
        self.gridLayout_12.addWidget(self.lcdNumber_Blue_Scale, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.groupBox_3)
        self.label_22.setObjectName("label_22")
        self.gridLayout_12.addWidget(self.label_22, 2, 0, 1, 1)
        self.BlueSlider_Scale = QtWidgets.QSlider(self.groupBox_3)
        self.BlueSlider_Scale.setMaximum(255)
        self.BlueSlider_Scale.setProperty("value", 50)
        self.BlueSlider_Scale.setOrientation(QtCore.Qt.Horizontal)
        self.BlueSlider_Scale.setObjectName("BlueSlider_Scale")
        self.gridLayout_12.addWidget(self.BlueSlider_Scale, 2, 1, 1, 1)
        self.TrancSlider_Scale = QtWidgets.QSlider(self.groupBox_3)
        self.TrancSlider_Scale.setMaximum(255)
        self.TrancSlider_Scale.setProperty("value", 255)
        self.TrancSlider_Scale.setOrientation(QtCore.Qt.Horizontal)
        self.TrancSlider_Scale.setObjectName("TrancSlider_Scale")
        self.gridLayout_12.addWidget(self.TrancSlider_Scale, 3, 1, 1, 1)
        self.lcdNumber_Trancparency_Scale = QtWidgets.QLCDNumber(self.groupBox_3)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Trancparency_Scale.setFont(font)
        self.lcdNumber_Trancparency_Scale.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Trancparency_Scale.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Trancparency_Scale.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Trancparency_Scale.setLineWidth(0)
        self.lcdNumber_Trancparency_Scale.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Trancparency_Scale.setObjectName("lcdNumber_Trancparency_Scale")
        self.gridLayout_12.addWidget(self.lcdNumber_Trancparency_Scale, 3, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.groupBox_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_12.addWidget(self.label_23, 0, 0, 1, 1)
        self.RedSlider_Scale = QtWidgets.QSlider(self.groupBox_3)
        self.RedSlider_Scale.setMaximum(255)
        self.RedSlider_Scale.setProperty("value", 50)
        self.RedSlider_Scale.setOrientation(QtCore.Qt.Horizontal)
        self.RedSlider_Scale.setObjectName("RedSlider_Scale")
        self.gridLayout_12.addWidget(self.RedSlider_Scale, 0, 1, 1, 1)
        self.gridLayout_11.addLayout(self.gridLayout_12, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.gridLayout_14 = QtWidgets.QGridLayout()
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setObjectName("label_24")
        self.gridLayout_14.addWidget(self.label_24, 1, 0, 1, 1)
        self.lcdNumber_Red_Display = QtWidgets.QLCDNumber(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Red_Display.setFont(font)
        self.lcdNumber_Red_Display.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Red_Display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Red_Display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Red_Display.setLineWidth(0)
        self.lcdNumber_Red_Display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Red_Display.setObjectName("lcdNumber_Red_Display")
        self.gridLayout_14.addWidget(self.lcdNumber_Red_Display, 0, 2, 1, 1)
        self.GreenSlider_Display = QtWidgets.QSlider(self.groupBox_4)
        self.GreenSlider_Display.setMaximum(255)
        self.GreenSlider_Display.setProperty("value", 50)
        self.GreenSlider_Display.setOrientation(QtCore.Qt.Horizontal)
        self.GreenSlider_Display.setObjectName("GreenSlider_Display")
        self.gridLayout_14.addWidget(self.GreenSlider_Display, 1, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setObjectName("label_25")
        self.gridLayout_14.addWidget(self.label_25, 3, 0, 1, 1)
        self.lcdNumber_Green_Display = QtWidgets.QLCDNumber(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Green_Display.setFont(font)
        self.lcdNumber_Green_Display.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Green_Display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Green_Display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Green_Display.setLineWidth(0)
        self.lcdNumber_Green_Display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Green_Display.setObjectName("lcdNumber_Green_Display")
        self.gridLayout_14.addWidget(self.lcdNumber_Green_Display, 1, 2, 1, 1)
        self.lcdNumber_Blue_Display = QtWidgets.QLCDNumber(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Blue_Display.setFont(font)
        self.lcdNumber_Blue_Display.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Blue_Display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Blue_Display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Blue_Display.setLineWidth(0)
        self.lcdNumber_Blue_Display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Blue_Display.setObjectName("lcdNumber_Blue_Display")
        self.gridLayout_14.addWidget(self.lcdNumber_Blue_Display, 2, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setObjectName("label_26")
        self.gridLayout_14.addWidget(self.label_26, 2, 0, 1, 1)
        self.BlueSlider_Display = QtWidgets.QSlider(self.groupBox_4)
        self.BlueSlider_Display.setMaximum(255)
        self.BlueSlider_Display.setProperty("value", 50)
        self.BlueSlider_Display.setOrientation(QtCore.Qt.Horizontal)
        self.BlueSlider_Display.setObjectName("BlueSlider_Display")
        self.gridLayout_14.addWidget(self.BlueSlider_Display, 2, 1, 1, 1)
        self.TrancSlider_Display = QtWidgets.QSlider(self.groupBox_4)
        self.TrancSlider_Display.setMaximum(255)
        self.TrancSlider_Display.setProperty("value", 255)
        self.TrancSlider_Display.setOrientation(QtCore.Qt.Horizontal)
        self.TrancSlider_Display.setObjectName("TrancSlider_Display")
        self.gridLayout_14.addWidget(self.TrancSlider_Display, 3, 1, 1, 1)
        self.lcdNumber_Trancparency_Display = QtWidgets.QLCDNumber(self.groupBox_4)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Trancparency_Display.setFont(font)
        self.lcdNumber_Trancparency_Display.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Trancparency_Display.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Trancparency_Display.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Trancparency_Display.setLineWidth(0)
        self.lcdNumber_Trancparency_Display.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Trancparency_Display.setObjectName("lcdNumber_Trancparency_Display")
        self.gridLayout_14.addWidget(self.lcdNumber_Trancparency_Display, 3, 2, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setObjectName("label_27")
        self.gridLayout_14.addWidget(self.label_27, 0, 0, 1, 1)
        self.RedSlider_Display = QtWidgets.QSlider(self.groupBox_4)
        self.RedSlider_Display.setMaximum(255)
        self.RedSlider_Display.setProperty("value", 50)
        self.RedSlider_Display.setOrientation(QtCore.Qt.Horizontal)
        self.RedSlider_Display.setObjectName("RedSlider_Display")
        self.gridLayout_14.addWidget(self.RedSlider_Display, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_14, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.gridLayout_15.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem3, 1, 0, 1, 1)
        self.Parameter.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_12 = QtWidgets.QLabel(self.tab_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_7.addWidget(self.label_12, 1, 0, 1, 1)
        self.lcdNumber_Red_2 = QtWidgets.QLCDNumber(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Red_2.setFont(font)
        self.lcdNumber_Red_2.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Red_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Red_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Red_2.setLineWidth(0)
        self.lcdNumber_Red_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Red_2.setObjectName("lcdNumber_Red_2")
        self.gridLayout_7.addWidget(self.lcdNumber_Red_2, 0, 2, 1, 1)
        self.MaxValueSlider = QtWidgets.QSlider(self.tab_2)
        self.MaxValueSlider.setMaximum(1100)
        self.MaxValueSlider.setSingleStep(10)
        self.MaxValueSlider.setProperty("value", 1100)
        self.MaxValueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MaxValueSlider.setObjectName("MaxValueSlider")
        self.gridLayout_7.addWidget(self.MaxValueSlider, 1, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.tab_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_7.addWidget(self.label_13, 3, 0, 1, 1)
        self.lcdNumber_Green_2 = QtWidgets.QLCDNumber(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Green_2.setFont(font)
        self.lcdNumber_Green_2.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Green_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Green_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Green_2.setLineWidth(0)
        self.lcdNumber_Green_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Green_2.setObjectName("lcdNumber_Green_2")
        self.gridLayout_7.addWidget(self.lcdNumber_Green_2, 1, 2, 1, 1)
        self.lcdNumber_Blue_2 = QtWidgets.QLCDNumber(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Blue_2.setFont(font)
        self.lcdNumber_Blue_2.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Blue_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Blue_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Blue_2.setLineWidth(0)
        self.lcdNumber_Blue_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Blue_2.setProperty("intValue", 11)
        self.lcdNumber_Blue_2.setObjectName("lcdNumber_Blue_2")
        self.gridLayout_7.addWidget(self.lcdNumber_Blue_2, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.tab_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_7.addWidget(self.label_14, 2, 0, 1, 1)
        self.MainGridSlider = QtWidgets.QSlider(self.tab_2)
        self.MainGridSlider.setMinimum(1)
        self.MainGridSlider.setMaximum(16)
        self.MainGridSlider.setProperty("value", 11)
        self.MainGridSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MainGridSlider.setObjectName("MainGridSlider")
        self.gridLayout_7.addWidget(self.MainGridSlider, 2, 1, 1, 1)
        self.TrancSlider_2 = QtWidgets.QSlider(self.tab_2)
        self.TrancSlider_2.setMaximum(255)
        self.TrancSlider_2.setProperty("value", 255)
        self.TrancSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.TrancSlider_2.setObjectName("TrancSlider_2")
        self.gridLayout_7.addWidget(self.TrancSlider_2, 3, 1, 1, 1)
        self.lcdNumber_Trancparency_2 = QtWidgets.QLCDNumber(self.tab_2)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.lcdNumber_Trancparency_2.setFont(font)
        self.lcdNumber_Trancparency_2.setStyleSheet("QLCDNumber {\n"
"    border: 1px solid black;\n"
"    border-radius: 5px;\n"
"    background-color: rgb(220, 220, 220);\n"
"    color: rgb(50, 50, 50);\n"
"}")
        self.lcdNumber_Trancparency_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcdNumber_Trancparency_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lcdNumber_Trancparency_2.setLineWidth(0)
        self.lcdNumber_Trancparency_2.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcdNumber_Trancparency_2.setObjectName("lcdNumber_Trancparency_2")
        self.gridLayout_7.addWidget(self.lcdNumber_Trancparency_2, 3, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.MinValueSlider = QtWidgets.QSlider(self.tab_2)
        self.MinValueSlider.setMaximum(100)
        self.MinValueSlider.setProperty("value", 0)
        self.MinValueSlider.setOrientation(QtCore.Qt.Horizontal)
        self.MinValueSlider.setObjectName("MinValueSlider")
        self.gridLayout_7.addWidget(self.MinValueSlider, 0, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_8.addItem(spacerItem4, 1, 0, 1, 1)
        self.Parameter.addTab(self.tab_2, "")
        self.gridLayout_4.addWidget(self.Parameter, 0, 4, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.Parameter.setCurrentIndex(0)
        self.ActualSlider.valueChanged['int'].connect(self.widget.update_value)
        self.ActualSlider.valueChanged['int'].connect(self.lcdNumber_4.display)
        self.horizontalSlider_5.valueChanged['int'].connect(self.lcdNumber_3.display)
        self.AussenRadiusSlider.valueChanged['int'].connect(self.lcdNumber_2.display)
        self.InnenRadiusSlider.valueChanged['int'].connect(self.lcdNumber.display)
        self.GaugeSizeSlider.valueChanged['int'].connect(self.lcdNumber_8.display)
        self.GaugeStartSlider.valueChanged['int'].connect(self.widget.set_start_scale_angle)
        self.GaugeSizeSlider.valueChanged['int'].connect(self.widget.set_total_scale_angle_size)
        self.AussenRadiusSlider.valueChanged['int'].connect(self.widget.set_gauge_color_outer_radius_factor)
        self.InnenRadiusSlider.valueChanged['int'].connect(self.widget.set_gauge_color_inner_radius_factor)
        self.GaugeStartSlider.valueChanged['int'].connect(self.lcdNumber_7.display)
        self.offsetSlider.valueChanged['int'].connect(self.widget.update_angle_offset)
        self.offsetSlider.valueChanged['int'].connect(self.lcdNumber_9.display)
        self.widget.valueChanged['int'].connect(self.ActualSlider.setValue)
        self.RedSlider_Needle.valueChanged['int'].connect(self.lcdNumber_Red_Needle.display)
        self.GreenSlider_Needle.valueChanged['int'].connect(self.lcdNumber_Green_Needle.display)
        self.BlueSlider_Needle.valueChanged['int'].connect(self.lcdNumber_Blue_Needle.display)
        self.TrancSlider_Needle.valueChanged['int'].connect(self.lcdNumber_Trancparency_Needle.display)
        self.MinValueSlider.valueChanged['int'].connect(self.widget.set_MinValue)
        self.MaxValueSlider.valueChanged['int'].connect(self.widget.set_MaxValue)
        self.MaxValueSlider.valueChanged['int'].connect(self.lcdNumber_Green_2.display)
        self.MinValueSlider.valueChanged['int'].connect(self.lcdNumber_Red_2.display)
        self.MainGridSlider.valueChanged['int'].connect(self.lcdNumber_Blue_2.display)
        self.TrancSlider_2.valueChanged['int'].connect(self.lcdNumber_Trancparency_2.display)
        self.RedSlider_NeedleDrag.valueChanged['int'].connect(self.lcdNumber_Red_NeedleDrag.display)
        self.GreenSlider_NeedleDrag.valueChanged['int'].connect(self.lcdNumber_Green_NeedleDrag.display)
        self.BlueSlider_NeedleDrag.valueChanged['int'].connect(self.lcdNumber_Blue_NeedleDrag.display)
        self.TrancSlider_NeedleDrag.valueChanged['int'].connect(self.lcdNumber_Trancparency_NeedleDrag.display)
        self.RedSlider_Scale.valueChanged['int'].connect(self.lcdNumber_Red_Scale.display)
        self.GreenSlider_Scale.valueChanged['int'].connect(self.lcdNumber_Green_Scale.display)
        self.BlueSlider_Scale.valueChanged['int'].connect(self.lcdNumber_Blue_Scale.display)
        self.TrancSlider_Scale.valueChanged['int'].connect(self.lcdNumber_Trancparency_Scale.display)
        self.RedSlider_Display.valueChanged['int'].connect(self.lcdNumber_Red_Display.display)
        self.GreenSlider_Display.valueChanged['int'].connect(self.lcdNumber_Green_Display.display)
        self.BlueSlider_Display.valueChanged['int'].connect(self.lcdNumber_Blue_Display.display)
        self.TrancSlider_Display.valueChanged['int'].connect(self.lcdNumber_Trancparency_Display.display)
        self.MainGridSlider.valueChanged['int'].connect(self.widget.set_scala_main_count)
        self.widget.valueChanged['int'].connect(self.ActualValue.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AnalogGaugeWidget_Demo"))
        self.label_2.setText(_translate("MainWindow", "Value 2"))
        self.label_5.setText(_translate("MainWindow", "Gauge Start"))
        self.label_3.setText(_translate("MainWindow", "AussenRadius"))
        self.label_4.setText(_translate("MainWindow", "InnenRadius"))
        self.label.setText(_translate("MainWindow", "Value"))
        self.label_7.setText(_translate("MainWindow", "Offset"))
        self.label_6.setText(_translate("MainWindow", "Gauge Size"))
        self.CB_ScaleText.setText(_translate("MainWindow", "Show Scale Text"))
        self.CB_Needle.setText(_translate("MainWindow", "Show Needle"))
        self.CB_ShowBarGraph.setText(_translate("MainWindow", "Show BarGraph"))
        self.CB_barGraph.setText(_translate("MainWindow", "Disable BarGraph Marker"))
        self.CB_ValueText.setText(_translate("MainWindow", "Show Display"))
        self.CB_CenterPoint.setText(_translate("MainWindow", "Show Center Point"))
        self.CB_Grid.setText(_translate("MainWindow", "Show Scale Grid"))
        self.CB_fineGrid.setText(_translate("MainWindow", "Show fine Scale Grid"))
        self.Parameter.setTabText(self.Parameter.indexOf(self.tab_3), _translate("MainWindow", "Setup"))
        self.groupBox.setTitle(_translate("MainWindow", "Needle: widget.set_NeedleColor(R=Red, G=Green, B=Blue, Transparency=Transparency)"))
        self.label_9.setText(_translate("MainWindow", "Green"))
        self.label_11.setText(_translate("MainWindow", "Trancparency"))
        self.label_10.setText(_translate("MainWindow", "Blue"))
        self.label_8.setText(_translate("MainWindow", "Red"))
        self.groupBox_2.setTitle(_translate("MainWindow", "NeedleDrag: widget.set_NeedleColorDrag(R=Red, G=Green, B=Blue, Transparency=Transparency)"))
        self.label_16.setText(_translate("MainWindow", "Green"))
        self.label_17.setText(_translate("MainWindow", "Trancparency"))
        self.label_18.setText(_translate("MainWindow", "Blue"))
        self.label_19.setText(_translate("MainWindow", "Red"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Skale"))
        self.label_20.setText(_translate("MainWindow", "Green"))
        self.label_21.setText(_translate("MainWindow", "Trancparency"))
        self.label_22.setText(_translate("MainWindow", "Blue"))
        self.label_23.setText(_translate("MainWindow", "Red"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Display Value"))
        self.label_24.setText(_translate("MainWindow", "Green"))
        self.label_25.setText(_translate("MainWindow", "Trancparency"))
        self.label_26.setText(_translate("MainWindow", "Blue"))
        self.label_27.setText(_translate("MainWindow", "Red"))
        self.Parameter.setTabText(self.Parameter.indexOf(self.tab), _translate("MainWindow", "Color"))
        self.label_12.setText(_translate("MainWindow", "Max Value"))
        self.label_13.setText(_translate("MainWindow", "Additional"))
        self.label_14.setText(_translate("MainWindow", "Grid Divider"))
        self.label_15.setText(_translate("MainWindow", "Min Value"))
        self.Parameter.setTabText(self.Parameter.indexOf(self.tab_2), _translate("MainWindow", "Min, Max Ranges"))

from analoggaugewidget import AnalogGaugeWidget
