# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powerMeter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(20, 20, 1041, 701))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lcd = QtWidgets.QLCDNumber(self.tab)
        self.lcd.setGeometry(QtCore.QRect(20, 450, 371, 131))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcd.setFont(font)
        self.lcd.setSmallDecimalPoint(False)
        self.lcd.setDigitCount(6)
        self.lcd.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd.setObjectName("lcd")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(20, 20, 501, 371))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.meterWidget = AnalogGaugeWidget(self.frame)
        self.meterWidget.setGeometry(QtCore.QRect(20, 30, 461, 321))
        self.meterWidget.setAutoFillBackground(True)
        self.meterWidget.setStyleSheet("")
        self.meterWidget.setObjectName("meterWidget")
        self.powerUnit = QtWidgets.QLabel(self.tab)
        self.powerUnit.setGeometry(QtCore.QRect(400, 510, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.powerUnit.setFont(font)
        self.powerUnit.setObjectName("powerUnit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(570, 20, 401, 371))
        self.groupBox_3.setObjectName("groupBox_3")
        self.freqBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.freqBox.setGeometry(QtCore.QRect(240, 40, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.freqBox.setFont(font)
        self.freqBox.setMaximum(6000)
        self.freqBox.setObjectName("freqBox")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.sensorPower = QtWidgets.QSpinBox(self.groupBox_3)
        self.sensorPower.setEnabled(False)
        self.sensorPower.setGeometry(QtCore.QRect(240, 80, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sensorPower.setFont(font)
        self.sensorPower.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sensorPower.setMinimum(-80)
        self.sensorPower.setMaximum(10)
        self.sensorPower.setObjectName("sensorPower")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.totalAttenuation = QtWidgets.QSpinBox(self.groupBox_3)
        self.totalAttenuation.setEnabled(False)
        self.totalAttenuation.setGeometry(QtCore.QRect(240, 120, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalAttenuation.setFont(font)
        self.totalAttenuation.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.totalAttenuation.setMinimum(-80)
        self.totalAttenuation.setMaximum(10)
        self.totalAttenuation.setObjectName("totalAttenuation")
        self.runButton = QtWidgets.QPushButton(self.groupBox_3)
        self.runButton.setGeometry(QtCore.QRect(80, 180, 83, 25))
        self.runButton.setObjectName("runButton")
        self.stopButton = QtWidgets.QPushButton(self.groupBox_3)
        self.stopButton.setGeometry(QtCore.QRect(210, 180, 83, 25))
        self.stopButton.setObjectName("stopButton")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(580, 100, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 420, 371, 16))
        self.horizontalSlider.setMinimum(-60)
        self.horizontalSlider.setMaximum(0)
        self.horizontalSlider.setProperty("value", -60)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tooLow = QtWidgets.QLabel(self.tab)
        self.tooLow.setGeometry(QtCore.QRect(20, 420, 62, 17))
        self.tooLow.setObjectName("tooLow")
        self.tooHigh = QtWidgets.QLabel(self.tab)
        self.tooHigh.setGeometry(QtCore.QRect(460, 420, 62, 17))
        self.tooHigh.setObjectName("tooHigh")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(170, 400, 221, 17))
        self.label_13.setObjectName("label_13")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setGeometry(QtCore.QRect(830, 0, 151, 261))
        self.groupBox.setObjectName("groupBox")
        self.AttenIDspin = QtWidgets.QSpinBox(self.groupBox)
        self.AttenIDspin.setGeometry(QtCore.QRect(70, 30, 61, 30))
        self.AttenIDspin.setMinimum(1)
        self.AttenIDspin.setObjectName("AttenIDspin")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(20, 30, 62, 31))
        self.label_11.setObjectName("label_11")
        self.useButton = QtWidgets.QPushButton(self.groupBox)
        self.useButton.setGeometry(QtCore.QRect(20, 70, 111, 25))
        self.useButton.setObjectName("useButton")
        self.unuseButton = QtWidgets.QPushButton(self.groupBox)
        self.unuseButton.setGeometry(QtCore.QRect(20, 100, 111, 25))
        self.unuseButton.setObjectName("unuseButton")
        self.importButton = QtWidgets.QPushButton(self.groupBox)
        self.importButton.setGeometry(QtCore.QRect(20, 140, 111, 25))
        self.importButton.setObjectName("importButton")
        self.editButton = QtWidgets.QPushButton(self.groupBox)
        self.editButton.setGeometry(QtCore.QRect(20, 180, 111, 25))
        self.editButton.setObjectName("editButton")
        self.deleteButton = QtWidgets.QPushButton(self.groupBox)
        self.deleteButton.setGeometry(QtCore.QRect(20, 220, 111, 25))
        self.deleteButton.setObjectName("deleteButton")
        self.browseDevices = QtWidgets.QTableView(self.tab_2)
        self.browseDevices.setGeometry(QtCore.QRect(20, 20, 781, 241))
        self.browseDevices.setObjectName("browseDevices")
        self.browseDevices.verticalHeader().setVisible(False)
        self.attenParameters = QtWidgets.QTableWidget(self.tab_2)
        self.attenParameters.setGeometry(QtCore.QRect(20, 290, 481, 251))
        self.attenParameters.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.attenParameters.setObjectName("attenParameters")
        self.attenParameters.setColumnCount(0)
        self.attenParameters.setRowCount(0)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(530, 270, 451, 271))
        self.groupBox_2.setObjectName("groupBox_2")
        self.Description = QtWidgets.QLineEdit(self.groupBox_2)
        self.Description.setGeometry(QtCore.QRect(100, 70, 331, 25))
        self.Description.setObjectName("Description")
        self.partID = QtWidgets.QLineEdit(self.groupBox_2)
        self.partID.setGeometry(QtCore.QRect(70, 30, 131, 25))
        self.partID.setObjectName("partID")
        self.nominalValue = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.nominalValue.setGeometry(QtCore.QRect(190, 150, 69, 26))
        self.nominalValue.setObjectName("nominalValue")
        self.minFreq = QtWidgets.QSpinBox(self.groupBox_2)
        self.minFreq.setGeometry(QtCore.QRect(190, 190, 71, 26))
        self.minFreq.setObjectName("minFreq")
        self.maxFreq = QtWidgets.QSpinBox(self.groupBox_2)
        self.maxFreq.setGeometry(QtCore.QRect(310, 190, 71, 26))
        self.maxFreq.setObjectName("maxFreq")
        self.serialID = QtWidgets.QLineEdit(self.groupBox_2)
        self.serialID.setGeometry(QtCore.QRect(270, 30, 161, 25))
        self.serialID.setObjectName("serialID")
        self.powerRating = QtWidgets.QSpinBox(self.groupBox_2)
        self.powerRating.setGeometry(QtCore.QRect(190, 110, 71, 26))
        self.powerRating.setObjectName("powerRating")
        self.updateButton = QtWidgets.QPushButton(self.groupBox_2)
        self.updateButton.setGeometry(QtCore.QRect(182, 230, 83, 25))
        self.updateButton.setObjectName("updateButton")
        self.cancelButton = QtWidgets.QPushButton(self.groupBox_2)
        self.cancelButton.setGeometry(QtCore.QRect(302, 230, 83, 25))
        self.cancelButton.setObjectName("cancelButton")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(10, 190, 181, 31))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setGeometry(QtCore.QRect(10, 150, 171, 30))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 181, 30))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(210, 30, 61, 31))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(280, 190, 31, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 76, 81, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 30, 51, 31))
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setGeometry(QtCore.QRect(60, 230, 83, 25))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.calTable = QtWidgets.QTableView(self.tab_3)
        self.calTable.setGeometry(QtCore.QRect(40, 50, 651, 192))
        self.calTable.setObjectName("calTable")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.powerUnit.setText(_translate("MainWindow", "dBm"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Settings"))
        self.freqBox.setSuffix(_translate("MainWindow", " MHz"))
        self.label_8.setText(_translate("MainWindow", "Freq to be measured"))
        self.sensorPower.setSuffix(_translate("MainWindow", " dBm"))
        self.label_10.setText(_translate("MainWindow", "Attenuation selected"))
        self.totalAttenuation.setSuffix(_translate("MainWindow", " dB"))
        self.runButton.setText(_translate("MainWindow", "Measure"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.label_9.setText(_translate("MainWindow", "Actual sensor power"))
        self.tooLow.setText(_translate("MainWindow", "Too Low"))
        self.tooHigh.setText(_translate("MainWindow", "Too High"))
        self.label_13.setText(_translate("MainWindow", "Sensor power for best accuracy"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Display"))
        self.groupBox.setTitle(_translate("MainWindow", "Attenuators / Couplers"))
        self.label_11.setText(_translate("MainWindow", "Select"))
        self.useButton.setText(_translate("MainWindow", "Use"))
        self.unuseButton.setText(_translate("MainWindow", "Stop Using"))
        self.importButton.setText(_translate("MainWindow", "Import S2P"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Edit or Add Attenuator / Coupler Details"))
        self.updateButton.setText(_translate("MainWindow", "Update"))
        self.cancelButton.setText(_translate("MainWindow", "Cancel"))
        self.label.setText(_translate("MainWindow", "Frequency Range MHz"))
        self.label_2.setText(_translate("MainWindow", "Nominal Attenuation dB"))
        self.label_3.setText(_translate("MainWindow", "Maximum Power Rating W"))
        self.label_4.setText(_translate("MainWindow", "Serial ID"))
        self.label_5.setText(_translate("MainWindow", "To"))
        self.label_6.setText(_translate("MainWindow", "Description"))
        self.label_7.setText(_translate("MainWindow", "Part ID"))
        self.pushButton.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Attenuators and Couplers"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Calibration"))

from analoggaugewidget import AnalogGaugeWidget
