# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powerMeter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.displayTab = QtWidgets.QWidget()
        self.displayTab.setObjectName("displayTab")
        self.frame = QtWidgets.QFrame(self.displayTab)
        self.frame.setGeometry(QtCore.QRect(10, 10, 340, 340))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.meterWidget = AnalogGaugeWidget(self.frame)
        self.meterWidget.setGeometry(QtCore.QRect(10, 10, 321, 321))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.meterWidget.sizePolicy().hasHeightForWidth())
        self.meterWidget.setSizePolicy(sizePolicy)
        self.meterWidget.setAutoFillBackground(True)
        self.meterWidget.setStyleSheet("")
        self.meterWidget.setObjectName("meterWidget")
        self.powerUnit = QtWidgets.QLabel(self.meterWidget)
        self.powerUnit.setGeometry(QtCore.QRect(210, 240, 90, 42))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.powerUnit.setFont(font)
        self.powerUnit.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.powerUnit.setAlignment(QtCore.Qt.AlignCenter)
        self.powerUnit.setObjectName("powerUnit")
        self.graphWidget = PlotWidget(self.displayTab)
        self.graphWidget.setGeometry(QtCore.QRect(410, 10, 531, 341))
        self.graphWidget.setAutoFillBackground(False)
        self.graphWidget.setStyleSheet("")
        self.graphWidget.setObjectName("graphWidget")
        self.label_3 = QtWidgets.QLabel(self.displayTab)
        self.label_3.setGeometry(QtCore.QRect(350, 310, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(self.displayTab)
        self.label_6.setGeometry(QtCore.QRect(940, 310, 60, 40))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.label_17 = QtWidgets.QLabel(self.displayTab)
        self.label_17.setGeometry(QtCore.QRect(370, 10, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.averaging = QtWidgets.QSlider(self.displayTab)
        self.averaging.setGeometry(QtCore.QRect(360, 40, 40, 271))
        self.averaging.setTabletTracking(False)
        self.averaging.setStyleSheet("")
        self.averaging.setMinimum(1)
        self.averaging.setMaximum(5000)
        self.averaging.setSingleStep(10)
        self.averaging.setPageStep(100)
        self.averaging.setProperty("value", 500)
        self.averaging.setTracking(False)
        self.averaging.setOrientation(QtCore.Qt.Vertical)
        self.averaging.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.averaging.setTickInterval(500)
        self.averaging.setObjectName("averaging")
        self.memorySize = QtWidgets.QSlider(self.displayTab)
        self.memorySize.setGeometry(QtCore.QRect(950, 40, 40, 271))
        self.memorySize.setStyleSheet("")
        self.memorySize.setMinimum(1)
        self.memorySize.setMaximum(100)
        self.memorySize.setSingleStep(10)
        self.memorySize.setPageStep(100)
        self.memorySize.setProperty("value", 10)
        self.memorySize.setTracking(False)
        self.memorySize.setOrientation(QtCore.Qt.Vertical)
        self.memorySize.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.memorySize.setTickInterval(10)
        self.memorySize.setObjectName("memorySize")
        self.label_19 = QtWidgets.QLabel(self.displayTab)
        self.label_19.setGeometry(QtCore.QRect(950, 10, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.GHzSlider = QtWidgets.QSlider(self.displayTab)
        self.GHzSlider.setEnabled(False)
        self.GHzSlider.setGeometry(QtCore.QRect(230, 360, 751, 20))
        self.GHzSlider.setMinimum(0)
        self.GHzSlider.setMaximum(6000)
        self.GHzSlider.setSingleStep(100)
        self.GHzSlider.setPageStep(500)
        self.GHzSlider.setProperty("value", 1296)
        self.GHzSlider.setTracking(True)
        self.GHzSlider.setOrientation(QtCore.Qt.Horizontal)
        self.GHzSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.GHzSlider.setTickInterval(100)
        self.GHzSlider.setObjectName("GHzSlider")
        self.layoutWidget = QtWidgets.QWidget(self.displayTab)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 410, 981, 87))
        self.layoutWidget.setObjectName("layoutWidget")
        self.measurements = QtWidgets.QGridLayout(self.layoutWidget)
        self.measurements.setContentsMargins(0, 0, 0, 0)
        self.measurements.setObjectName("measurements")
        self.totalLoss = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.totalLoss.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.totalLoss.setFont(font)
        self.totalLoss.setAutoFillBackground(False)
        self.totalLoss.setFrame(False)
        self.totalLoss.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.totalLoss.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.totalLoss.setDecimals(1)
        self.totalLoss.setSingleStep(0.01)
        self.totalLoss.setObjectName("totalLoss")
        self.measurements.addWidget(self.totalLoss, 0, 3, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.stopButton.setFont(font)
        self.stopButton.setObjectName("stopButton")
        self.measurements.addWidget(self.stopButton, 1, 2, 1, 1)
        self.inputPower = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.inputPower.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.inputPower.setFont(font)
        self.inputPower.setFrame(False)
        self.inputPower.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.inputPower.setReadOnly(True)
        self.inputPower.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.inputPower.setDecimals(1)
        self.inputPower.setMinimum(-70.0)
        self.inputPower.setMaximum(60.0)
        self.inputPower.setSingleStep(0.01)
        self.inputPower.setProperty("value", -70.0)
        self.inputPower.setObjectName("inputPower")
        self.measurements.addWidget(self.inputPower, 0, 5, 1, 1)
        self.runButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.runButton.setFont(font)
        self.runButton.setObjectName("runButton")
        self.measurements.addWidget(self.runButton, 1, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.measurements.addWidget(self.label_10, 0, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.measurements.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.measurements.addWidget(self.label_9, 0, 0, 1, 1)
        self.powerWatts = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.powerWatts.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.powerWatts.setFont(font)
        self.powerWatts.setFrame(False)
        self.powerWatts.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.powerWatts.setReadOnly(True)
        self.powerWatts.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.powerWatts.setDecimals(1)
        self.powerWatts.setMinimum(0.0)
        self.powerWatts.setMaximum(1000.0)
        self.powerWatts.setSingleStep(0.01)
        self.powerWatts.setProperty("value", 0.0)
        self.powerWatts.setObjectName("powerWatts")
        self.measurements.addWidget(self.powerWatts, 0, 6, 1, 1)
        self.warning = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.warning.setFont(font)
        self.warning.setStyleSheet("color: rgb(255, 0, 0);")
        self.warning.setAlignment(QtCore.Qt.AlignCenter)
        self.warning.setObjectName("warning")
        self.measurements.addWidget(self.warning, 1, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.measurements.addWidget(self.label_14, 1, 3, 1, 1)
        self.sensorPower = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.sensorPower.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sensorPower.setFont(font)
        self.sensorPower.setAutoFillBackground(False)
        self.sensorPower.setFrame(False)
        self.sensorPower.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.sensorPower.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sensorPower.setDecimals(1)
        self.sensorPower.setMinimum(-70.0)
        self.sensorPower.setMaximum(20.0)
        self.sensorPower.setSingleStep(0.01)
        self.sensorPower.setProperty("value", -70.0)
        self.sensorPower.setObjectName("sensorPower")
        self.measurements.addWidget(self.sensorPower, 0, 1, 1, 1)
        self.calQualLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(12)
        self.calQualLabel.setFont(font)
        self.calQualLabel.setAutoFillBackground(False)
        self.calQualLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.calQualLabel.setLineWidth(1)
        self.calQualLabel.setText("")
        self.calQualLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.calQualLabel.setObjectName("calQualLabel")
        self.measurements.addWidget(self.calQualLabel, 1, 4, 1, 1)
        self.spiNoise = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spiNoise.setFont(font)
        self.spiNoise.setAutoFillBackground(False)
        self.spiNoise.setStyleSheet("color: rgb(255, 0, 0);")
        self.spiNoise.setText("")
        self.spiNoise.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spiNoise.setObjectName("spiNoise")
        self.measurements.addWidget(self.spiNoise, 1, 5, 1, 1)
        self.measurementRate = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.measurementRate.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.measurementRate.setFont(font)
        self.measurementRate.setFrame(False)
        self.measurementRate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.measurementRate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.measurementRate.setDecimals(0)
        self.measurementRate.setMaximum(10000.0)
        self.measurementRate.setObjectName("measurementRate")
        self.measurements.addWidget(self.measurementRate, 1, 6, 1, 1)
        self.freqBox = QtWidgets.QSpinBox(self.displayTab)
        self.freqBox.setEnabled(False)
        self.freqBox.setGeometry(QtCore.QRect(920, 380, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.freqBox.setFont(font)
        self.freqBox.setFrame(False)
        self.freqBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.freqBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.freqBox.setKeyboardTracking(False)
        self.freqBox.setMinimum(0)
        self.freqBox.setMaximum(6000)
        self.freqBox.setSingleStep(100)
        self.freqBox.setProperty("value", 1296)
        self.freqBox.setObjectName("freqBox")
        self.HF = QtWidgets.QRadioButton(self.displayTab)
        self.HF.setGeometry(QtCore.QRect(230, 380, 51, 23))
        self.HF.setObjectName("HF")
        self.hamBands = QtWidgets.QButtonGroup(MainWindow)
        self.hamBands.setObjectName("hamBands")
        self.hamBands.addButton(self.HF)
        self.m6 = QtWidgets.QRadioButton(self.displayTab)
        self.m6.setGeometry(QtCore.QRect(280, 380, 51, 23))
        self.m6.setObjectName("m6")
        self.hamBands.addButton(self.m6)
        self.m4 = QtWidgets.QRadioButton(self.displayTab)
        self.m4.setGeometry(QtCore.QRect(340, 380, 51, 23))
        self.m4.setObjectName("m4")
        self.hamBands.addButton(self.m4)
        self.m2 = QtWidgets.QRadioButton(self.displayTab)
        self.m2.setGeometry(QtCore.QRect(400, 380, 51, 23))
        self.m2.setObjectName("m2")
        self.hamBands.addButton(self.m2)
        self.cm70 = QtWidgets.QRadioButton(self.displayTab)
        self.cm70.setGeometry(QtCore.QRect(450, 380, 61, 23))
        self.cm70.setObjectName("cm70")
        self.hamBands.addButton(self.cm70)
        self.cm23 = QtWidgets.QRadioButton(self.displayTab)
        self.cm23.setGeometry(QtCore.QRect(520, 380, 61, 23))
        self.cm23.setChecked(True)
        self.cm23.setObjectName("cm23")
        self.hamBands.addButton(self.cm23)
        self.cm13 = QtWidgets.QRadioButton(self.displayTab)
        self.cm13.setGeometry(QtCore.QRect(590, 380, 61, 23))
        self.cm13.setObjectName("cm13")
        self.hamBands.addButton(self.cm13)
        self.cm9 = QtWidgets.QRadioButton(self.displayTab)
        self.cm9.setGeometry(QtCore.QRect(660, 380, 61, 23))
        self.cm9.setObjectName("cm9")
        self.hamBands.addButton(self.cm9)
        self.cm6 = QtWidgets.QRadioButton(self.displayTab)
        self.cm6.setGeometry(QtCore.QRect(730, 380, 61, 23))
        self.cm6.setObjectName("cm6")
        self.hamBands.addButton(self.cm6)
        self.noBand = QtWidgets.QRadioButton(self.displayTab)
        self.noBand.setGeometry(QtCore.QRect(790, 380, 121, 23))
        self.noBand.setObjectName("noBand")
        self.hamBands.addButton(self.noBand)
        self.autoRangeButton = QtWidgets.QRadioButton(self.displayTab)
        self.autoRangeButton.setGeometry(QtCore.QRect(10, 380, 61, 23))
        self.autoRangeButton.setChecked(True)
        self.autoRangeButton.setObjectName("autoRangeButton")
        self.dBmRange = QtWidgets.QButtonGroup(MainWindow)
        self.dBmRange.setObjectName("dBmRange")
        self.dBmRange.addButton(self.autoRangeButton)
        self.manualRangeButton = QtWidgets.QRadioButton(self.displayTab)
        self.manualRangeButton.setGeometry(QtCore.QRect(70, 380, 71, 23))
        self.manualRangeButton.setObjectName("manualRangeButton")
        self.dBmRange.addButton(self.manualRangeButton)
        self.horizontalSlider = QtWidgets.QSlider(self.displayTab)
        self.horizontalSlider.setGeometry(QtCore.QRect(10, 360, 201, 20))
        self.horizontalSlider.setMinimum(-60)
        self.horizontalSlider.setMaximum(60)
        self.horizontalSlider.setSingleStep(10)
        self.horizontalSlider.setPageStep(30)
        self.horizontalSlider.setSliderPosition(-60)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.rangeBox = QtWidgets.QSpinBox(self.displayTab)
        self.rangeBox.setEnabled(False)
        self.rangeBox.setGeometry(QtCore.QRect(150, 380, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.rangeBox.setFont(font)
        self.rangeBox.setFrame(False)
        self.rangeBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.rangeBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rangeBox.setKeyboardTracking(False)
        self.rangeBox.setMinimum(-60)
        self.rangeBox.setMaximum(60)
        self.rangeBox.setSingleStep(10)
        self.rangeBox.setProperty("value", -60)
        self.rangeBox.setObjectName("rangeBox")
        self.tabWidget.addTab(self.displayTab, "")
        self.attenuationTab = QtWidgets.QWidget()
        self.attenuationTab.setObjectName("attenuationTab")
        self.groupBox_2 = QtWidgets.QGroupBox(self.attenuationTab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 270, 491, 221))
        self.groupBox_2.setObjectName("groupBox_2")
        self.deviceParameters = QtWidgets.QTableView(self.groupBox_2)
        self.deviceParameters.setGeometry(QtCore.QRect(140, 30, 331, 181))
        self.deviceParameters.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.deviceParameters.setAlternatingRowColors(True)
        self.deviceParameters.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.deviceParameters.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.deviceParameters.setGridStyle(QtCore.Qt.DotLine)
        self.deviceParameters.setSortingEnabled(True)
        self.deviceParameters.setObjectName("deviceParameters")
        self.deviceParameters.verticalHeader().setVisible(False)
        self.importS2P = QtWidgets.QPushButton(self.groupBox_2)
        self.importS2P.setGeometry(QtCore.QRect(20, 40, 91, 25))
        self.importS2P.setObjectName("importS2P")
        self.addRow = QtWidgets.QPushButton(self.groupBox_2)
        self.addRow.setGeometry(QtCore.QRect(20, 80, 91, 25))
        self.addRow.setObjectName("addRow")
        self.deleteRow = QtWidgets.QPushButton(self.groupBox_2)
        self.deleteRow.setGeometry(QtCore.QRect(20, 180, 91, 25))
        self.deleteRow.setObjectName("deleteRow")
        self.saveData = QtWidgets.QPushButton(self.groupBox_2)
        self.saveData.setGeometry(QtCore.QRect(20, 120, 91, 25))
        self.saveData.setObjectName("saveData")
        self.groupBox_4 = QtWidgets.QGroupBox(self.attenuationTab)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 10, 991, 251))
        self.groupBox_4.setObjectName("groupBox_4")
        self.deleteDevice = QtWidgets.QPushButton(self.groupBox_4)
        self.deleteDevice.setGeometry(QtCore.QRect(460, 210, 111, 25))
        self.deleteDevice.setObjectName("deleteDevice")
        self.addDevice = QtWidgets.QPushButton(self.groupBox_4)
        self.addDevice.setGeometry(QtCore.QRect(170, 210, 101, 25))
        self.addDevice.setObjectName("addDevice")
        self.browseDevices = QtWidgets.QTableView(self.groupBox_4)
        self.browseDevices.setGeometry(QtCore.QRect(20, 30, 951, 171))
        self.browseDevices.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.browseDevices.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.browseDevices.setAlternatingRowColors(True)
        self.browseDevices.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.browseDevices.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.browseDevices.setSortingEnabled(True)
        self.browseDevices.setObjectName("browseDevices")
        self.browseDevices.verticalHeader().setVisible(False)
        self.showParameters = QtWidgets.QPushButton(self.groupBox_4)
        self.showParameters.setGeometry(QtCore.QRect(20, 210, 131, 25))
        self.showParameters.setObjectName("showParameters")
        self.saveDevice = QtWidgets.QPushButton(self.groupBox_4)
        self.saveDevice.setGeometry(QtCore.QRect(290, 210, 111, 25))
        self.saveDevice.setObjectName("saveDevice")
        self.tabWidget.addTab(self.attenuationTab, "")
        self.calibrationTab = QtWidgets.QWidget()
        self.calibrationTab.setObjectName("calibrationTab")
        self.groupBox_5 = QtWidgets.QGroupBox(self.calibrationTab)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 10, 991, 471))
        self.groupBox_5.setObjectName("groupBox_5")
        self.calTable = QtWidgets.QTableView(self.groupBox_5)
        self.calTable.setGeometry(QtCore.QRect(160, 30, 811, 431))
        self.calTable.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.calTable.setAlternatingRowColors(True)
        self.calTable.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.calTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.calTable.setSortingEnabled(True)
        self.calTable.setObjectName("calTable")
        self.calTable.verticalHeader().setVisible(False)
        self.addCalData = QtWidgets.QPushButton(self.groupBox_5)
        self.addCalData.setGeometry(QtCore.QRect(20, 40, 91, 25))
        self.addCalData.setObjectName("addCalData")
        self.deleteCal = QtWidgets.QPushButton(self.groupBox_5)
        self.deleteCal.setGeometry(QtCore.QRect(20, 80, 91, 25))
        self.deleteCal.setObjectName("deleteCal")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 130, 131, 191))
        self.groupBox_6.setObjectName("groupBox_6")
        self.measure = QtWidgets.QPushButton(self.groupBox_6)
        self.measure.setGeometry(QtCore.QRect(20, 100, 91, 25))
        self.measure.setObjectName("measure")
        self.vHigh = QtWidgets.QRadioButton(self.groupBox_6)
        self.vHigh.setGeometry(QtCore.QRect(20, 30, 101, 23))
        self.vHigh.setChecked(True)
        self.vHigh.setObjectName("vHigh")
        self.vLow = QtWidgets.QRadioButton(self.groupBox_6)
        self.vLow.setGeometry(QtCore.QRect(20, 60, 91, 23))
        self.vLow.setObjectName("vLow")
        self.calibrate = QtWidgets.QPushButton(self.groupBox_6)
        self.calibrate.setGeometry(QtCore.QRect(20, 140, 91, 25))
        self.calibrate.setObjectName("calibrate")
        self.tabWidget.addTab(self.calibrationTab, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.stopButton.clicked.connect(self.powerWatts.clear)
        self.GHzSlider.valueChanged['int'].connect(self.freqBox.setValue)
        self.freqBox.valueChanged['int'].connect(self.GHzSlider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.measurementRate, self.addRow)
        MainWindow.setTabOrder(self.addRow, self.deleteRow)
        MainWindow.setTabOrder(self.deleteRow, self.saveData)
        MainWindow.setTabOrder(self.saveData, self.deleteDevice)
        MainWindow.setTabOrder(self.deleteDevice, self.addDevice)
        MainWindow.setTabOrder(self.addDevice, self.browseDevices)
        MainWindow.setTabOrder(self.browseDevices, self.showParameters)
        MainWindow.setTabOrder(self.showParameters, self.saveDevice)
        MainWindow.setTabOrder(self.saveDevice, self.calTable)
        MainWindow.setTabOrder(self.calTable, self.addCalData)
        MainWindow.setTabOrder(self.addCalData, self.deleteCal)
        MainWindow.setTabOrder(self.deleteCal, self.measure)
        MainWindow.setTabOrder(self.measure, self.vHigh)
        MainWindow.setTabOrder(self.vHigh, self.vLow)
        MainWindow.setTabOrder(self.vLow, self.calibrate)
        MainWindow.setTabOrder(self.calibrate, self.importS2P)
        MainWindow.setTabOrder(self.importS2P, self.deviceParameters)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "G4IXT Qt RF Power Meter"))
        self.powerUnit.setText(_translate("MainWindow", "Auto"))
        self.label_3.setText(_translate("MainWindow", "Meter\n"
"Average"))
        self.label_6.setText(_translate("MainWindow", "Memory\n"
"Size"))
        self.label_17.setText(_translate("MainWindow", "5kS"))
        self.label_19.setText(_translate("MainWindow", "100kS"))
        self.totalLoss.setSuffix(_translate("MainWindow", " dB"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.inputPower.setSuffix(_translate("MainWindow", " dBm"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.label_10.setText(_translate("MainWindow", "Attenuation"))
        self.label_12.setText(_translate("MainWindow", "Measured RF Power"))
        self.label_9.setText(_translate("MainWindow", "Power at Sensor"))
        self.powerWatts.setSuffix(_translate("MainWindow", " W"))
        self.warning.setText(_translate("MainWindow", "+10dBm Max"))
        self.label_14.setText(_translate("MainWindow", "Calibration Source:"))
        self.sensorPower.setSuffix(_translate("MainWindow", " dBm"))
        self.measurementRate.setSuffix(_translate("MainWindow", " S/s"))
        self.freqBox.setSuffix(_translate("MainWindow", " MHz"))
        self.HF.setText(_translate("MainWindow", "HF"))
        self.m6.setText(_translate("MainWindow", "6m"))
        self.m4.setText(_translate("MainWindow", "4m"))
        self.m2.setText(_translate("MainWindow", "2m"))
        self.cm70.setText(_translate("MainWindow", "70cm"))
        self.cm23.setText(_translate("MainWindow", "23cm"))
        self.cm13.setText(_translate("MainWindow", "13cm"))
        self.cm9.setText(_translate("MainWindow", "9cm"))
        self.cm6.setText(_translate("MainWindow", "6cm"))
        self.noBand.setText(_translate("MainWindow", "Set Frequency"))
        self.autoRangeButton.setText(_translate("MainWindow", "Auto"))
        self.manualRangeButton.setText(_translate("MainWindow", "Manual"))
        self.rangeBox.setSuffix(_translate("MainWindow", " dBm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.displayTab), _translate("MainWindow", "Display"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Device parameters"))
        self.importS2P.setText(_translate("MainWindow", "Import S2P"))
        self.addRow.setText(_translate("MainWindow", "Add Row"))
        self.deleteRow.setText(_translate("MainWindow", "Delete Data"))
        self.saveData.setText(_translate("MainWindow", "Save Data"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Devices available to use with power sensor"))
        self.deleteDevice.setText(_translate("MainWindow", "Delete Device"))
        self.addDevice.setText(_translate("MainWindow", "Add Row"))
        self.showParameters.setText(_translate("MainWindow", "Show parameters"))
        self.saveDevice.setText(_translate("MainWindow", "Save Device"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.attenuationTab), _translate("MainWindow", "Attenuation"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Sensor calibration data"))
        self.addCalData.setText(_translate("MainWindow", "Add Row"))
        self.deleteCal.setText(_translate("MainWindow", "Delete Row"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Calibration"))
        self.measure.setText(_translate("MainWindow", "Measure"))
        self.vHigh.setText(_translate("MainWindow", "High Code"))
        self.vLow.setText(_translate("MainWindow", "Low Code"))
        self.calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibrationTab), _translate("MainWindow", "Calibration"))

from analoggaugewidget import AnalogGaugeWidget
from pyqtgraph import PlotWidget
