# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'powerMeter.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1083, 765)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1041, 701))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.lcd = QtWidgets.QLCDNumber(self.tab)
        self.lcd.setGeometry(QtCore.QRect(590, 280, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lcd.setFont(font)
        self.lcd.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lcd.setSmallDecimalPoint(False)
        self.lcd.setDigitCount(4)
        self.lcd.setMode(QtWidgets.QLCDNumber.Dec)
        self.lcd.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.lcd.setObjectName("lcd")
        self.frame = QtWidgets.QFrame(self.tab)
        self.frame.setGeometry(QtCore.QRect(20, 20, 501, 371))
        self.frame.setAutoFillBackground(True)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setMidLineWidth(2)
        self.frame.setObjectName("frame")
        self.meterWidget = AnalogGaugeWidget(self.frame)
        self.meterWidget.setGeometry(QtCore.QRect(20, 30, 461, 321))
        self.meterWidget.setAutoFillBackground(True)
        self.meterWidget.setStyleSheet("")
        self.meterWidget.setObjectName("meterWidget")
        self.label_4 = QtWidgets.QLabel(self.meterWidget)
        self.label_4.setGeometry(QtCore.QRect(360, 246, 91, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.powerUnit = QtWidgets.QLabel(self.tab)
        self.powerUnit.setGeometry(QtCore.QRect(850, 310, 101, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        self.powerUnit.setFont(font)
        self.powerUnit.setObjectName("powerUnit")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(570, 20, 431, 221))
        self.groupBox_3.setObjectName("groupBox_3")
        self.freqBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.freqBox.setGeometry(QtCore.QRect(240, 40, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.freqBox.setFont(font)
        self.freqBox.setMaximum(6000)
        self.freqBox.setObjectName("freqBox")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 40, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.sensorPower = QtWidgets.QSpinBox(self.groupBox_3)
        self.sensorPower.setEnabled(False)
        self.sensorPower.setGeometry(QtCore.QRect(240, 80, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.sensorPower.setFont(font)
        self.sensorPower.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.sensorPower.setMinimum(-80)
        self.sensorPower.setMaximum(10)
        self.sensorPower.setObjectName("sensorPower")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 120, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.totalAttenuation = QtWidgets.QSpinBox(self.groupBox_3)
        self.totalAttenuation.setEnabled(False)
        self.totalAttenuation.setGeometry(QtCore.QRect(240, 120, 151, 26))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.totalAttenuation.setFont(font)
        self.totalAttenuation.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.totalAttenuation.setMinimum(-80)
        self.totalAttenuation.setMaximum(10)
        self.totalAttenuation.setObjectName("totalAttenuation")
        self.runButton = QtWidgets.QPushButton(self.groupBox_3)
        self.runButton.setGeometry(QtCore.QRect(80, 170, 83, 25))
        self.runButton.setObjectName("runButton")
        self.stopButton = QtWidgets.QPushButton(self.groupBox_3)
        self.stopButton.setGeometry(QtCore.QRect(230, 170, 83, 25))
        self.stopButton.setObjectName("stopButton")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(580, 100, 221, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalSlider = QtWidgets.QSlider(self.tab)
        self.horizontalSlider.setEnabled(False)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 420, 371, 16))
        self.horizontalSlider.setMinimum(-60)
        self.horizontalSlider.setMaximum(0)
        self.horizontalSlider.setProperty("value", -60)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setInvertedAppearance(False)
        self.horizontalSlider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.tooLow = QtWidgets.QLabel(self.tab)
        self.tooLow.setGeometry(QtCore.QRect(20, 420, 62, 17))
        self.tooLow.setObjectName("tooLow")
        self.tooHigh = QtWidgets.QLabel(self.tab)
        self.tooHigh.setGeometry(QtCore.QRect(460, 420, 62, 17))
        self.tooHigh.setObjectName("tooHigh")
        self.label_13 = QtWidgets.QLabel(self.tab)
        self.label_13.setGeometry(QtCore.QRect(170, 400, 221, 17))
        self.label_13.setObjectName("label_13")
        self.powerGraph = PlotWidget(self.tab)
        self.powerGraph.setGeometry(QtCore.QRect(30, 460, 971, 191))
        self.powerGraph.setObjectName("powerGraph")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(570, 250, 431, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_3 = QtWidgets.QLabel(self.tab)
        self.label_3.setGeometry(QtCore.QRect(570, 420, 361, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.groupBox.raise_()
        self.lcd.raise_()
        self.frame.raise_()
        self.powerUnit.raise_()
        self.groupBox_3.raise_()
        self.label_9.raise_()
        self.horizontalSlider.raise_()
        self.tooLow.raise_()
        self.tooHigh.raise_()
        self.label_13.raise_()
        self.powerGraph.raise_()
        self.label_3.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 350, 1001, 291))
        self.groupBox_2.setObjectName("groupBox_2")
        self.deviceParameters = QtWidgets.QTableView(self.groupBox_2)
        self.deviceParameters.setGeometry(QtCore.QRect(140, 30, 841, 251))
        self.deviceParameters.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.deviceParameters.setAlternatingRowColors(True)
        self.deviceParameters.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.deviceParameters.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.deviceParameters.setGridStyle(QtCore.Qt.DotLine)
        self.deviceParameters.setSortingEnabled(True)
        self.deviceParameters.setObjectName("deviceParameters")
        self.deviceParameters.verticalHeader().setVisible(False)
        self.importS2P = QtWidgets.QPushButton(self.groupBox_2)
        self.importS2P.setGeometry(QtCore.QRect(20, 40, 91, 25))
        self.importS2P.setObjectName("importS2P")
        self.addRow = QtWidgets.QPushButton(self.groupBox_2)
        self.addRow.setGeometry(QtCore.QRect(20, 80, 91, 25))
        self.addRow.setObjectName("addRow")
        self.deleteRow = QtWidgets.QPushButton(self.groupBox_2)
        self.deleteRow.setGeometry(QtCore.QRect(20, 180, 91, 25))
        self.deleteRow.setObjectName("deleteRow")
        self.saveData = QtWidgets.QPushButton(self.groupBox_2)
        self.saveData.setGeometry(QtCore.QRect(20, 120, 91, 25))
        self.saveData.setObjectName("saveData")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_4.setGeometry(QtCore.QRect(20, 10, 1001, 321))
        self.groupBox_4.setObjectName("groupBox_4")
        self.deleteDevice = QtWidgets.QPushButton(self.groupBox_4)
        self.deleteDevice.setGeometry(QtCore.QRect(460, 280, 111, 25))
        self.deleteDevice.setObjectName("deleteDevice")
        self.addDevice = QtWidgets.QPushButton(self.groupBox_4)
        self.addDevice.setGeometry(QtCore.QRect(170, 280, 101, 25))
        self.addDevice.setObjectName("addDevice")
        self.browseDevices = QtWidgets.QTableView(self.groupBox_4)
        self.browseDevices.setGeometry(QtCore.QRect(20, 30, 961, 241))
        self.browseDevices.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.browseDevices.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.browseDevices.setAlternatingRowColors(True)
        self.browseDevices.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.browseDevices.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.browseDevices.setSortingEnabled(True)
        self.browseDevices.setObjectName("browseDevices")
        self.browseDevices.verticalHeader().setVisible(False)
        self.showParameters = QtWidgets.QPushButton(self.groupBox_4)
        self.showParameters.setGeometry(QtCore.QRect(20, 280, 131, 25))
        self.showParameters.setObjectName("showParameters")
        self.saveDevice = QtWidgets.QPushButton(self.groupBox_4)
        self.saveDevice.setGeometry(QtCore.QRect(290, 280, 111, 25))
        self.saveDevice.setObjectName("saveDevice")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 10, 1001, 531))
        self.groupBox_5.setObjectName("groupBox_5")
        self.calTable = QtWidgets.QTableView(self.groupBox_5)
        self.calTable.setGeometry(QtCore.QRect(210, 30, 771, 371))
        self.calTable.setEditTriggers(QtWidgets.QAbstractItemView.CurrentChanged|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.SelectedClicked)
        self.calTable.setAlternatingRowColors(True)
        self.calTable.setSortingEnabled(True)
        self.calTable.setObjectName("calTable")
        self.calTable.verticalHeader().setVisible(False)
        self.addCalData = QtWidgets.QPushButton(self.groupBox_5)
        self.addCalData.setGeometry(QtCore.QRect(60, 40, 91, 25))
        self.addCalData.setObjectName("addCalData")
        self.deleteCal = QtWidgets.QPushButton(self.groupBox_5)
        self.deleteCal.setGeometry(QtCore.QRect(60, 80, 91, 25))
        self.deleteCal.setObjectName("deleteCal")
        self.groupBox_6 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_6.setGeometry(QtCore.QRect(20, 120, 171, 131))
        self.groupBox_6.setObjectName("groupBox_6")
        self.calibrate = QtWidgets.QPushButton(self.groupBox_6)
        self.calibrate.setGeometry(QtCore.QRect(40, 90, 91, 25))
        self.calibrate.setObjectName("calibrate")
        self.vHigh = QtWidgets.QRadioButton(self.groupBox_6)
        self.vHigh.setGeometry(QtCore.QRect(10, 30, 71, 23))
        self.vHigh.setChecked(True)
        self.vHigh.setObjectName("vHigh")
        self.vLow = QtWidgets.QRadioButton(self.groupBox_6)
        self.vLow.setGeometry(QtCore.QRect(10, 60, 81, 23))
        self.vLow.setObjectName("vLow")
        self.groupBox_7 = QtWidgets.QGroupBox(self.groupBox_5)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 270, 171, 131))
        self.groupBox_7.setObjectName("groupBox_7")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 106, 23))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_2.setGeometry(QtCore.QRect(10, 60, 151, 23))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.groupBox_7)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 90, 141, 23))
        self.radioButton_3.setObjectName("radioButton_3")
        self.tabWidget.addTab(self.tab_3, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1083, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "W"))
        self.powerUnit.setText(_translate("MainWindow", "dBm"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Settings"))
        self.freqBox.setSuffix(_translate("MainWindow", " MHz"))
        self.label_8.setText(_translate("MainWindow", "Freq to be measured"))
        self.sensorPower.setSuffix(_translate("MainWindow", " dBm"))
        self.label_10.setText(_translate("MainWindow", "Attenuation at Freq"))
        self.totalAttenuation.setSuffix(_translate("MainWindow", " dB"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.stopButton.setText(_translate("MainWindow", "Stop"))
        self.label_9.setText(_translate("MainWindow", "Actual sensor power"))
        self.tooLow.setText(_translate("MainWindow", "Too Low"))
        self.tooHigh.setText(_translate("MainWindow", "Too High"))
        self.label_13.setText(_translate("MainWindow", "Sensor power for best accuracy"))
        self.groupBox.setTitle(_translate("MainWindow", "Power calculated using all factors at selected Frequency"))
        self.label_3.setText(_translate("MainWindow", "Sensor Absolute Maximum input Power is +12dBm"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Display"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Device parameters"))
        self.importS2P.setText(_translate("MainWindow", "Import S2P"))
        self.addRow.setText(_translate("MainWindow", "Add Row"))
        self.deleteRow.setText(_translate("MainWindow", "Delete Data"))
        self.saveData.setText(_translate("MainWindow", "Save Data"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Devices available to use with power sensor"))
        self.deleteDevice.setText(_translate("MainWindow", "Delete Device"))
        self.addDevice.setText(_translate("MainWindow", "Add Row"))
        self.showParameters.setText(_translate("MainWindow", "Show parameters"))
        self.saveDevice.setText(_translate("MainWindow", "Save Device"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Devices"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Sensor calibration data"))
        self.addCalData.setText(_translate("MainWindow", "Add Row"))
        self.deleteCal.setText(_translate("MainWindow", "Delete Row"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Calibrate sensor"))
        self.calibrate.setText(_translate("MainWindow", "Calibrate"))
        self.vHigh.setText(_translate("MainWindow", "V High"))
        self.vLow.setText(_translate("MainWindow", "V Low"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Cal Quality"))
        self.radioButton.setText(_translate("MainWindow", "Datasheet"))
        self.radioButton_2.setText(_translate("MainWindow", "Uncalibrated meter"))
        self.radioButton_3.setText(_translate("MainWindow", "calibrated meter"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "Calibration"))

from analoggaugewidget import AnalogGaugeWidget
from pyqtgraph import PlotWidget
